version: '3.8'

services:
  postgres:
    container_name: ccca-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
  rabbitmq:
    container_name: ccca-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest